CREATE DATABASE QLCuaHangTT
ON PRIMARY
(
NAME = QLCHTT_Data,
FILENAME = 'D:\DoAnPTUD\QLCHTT_Data.mdf',
SIZE = 20MB,
MAXSIZE = 30MB,
FILEGROWTH = 20%
)
LOG ON (
NAME = QLCHTT_LOG,
FILENAME = 'D:\DoAnPTUD\QLCHTT_LOG.ldf',
SIZE = 3MB,
MAXSIZE= 5MB,
FILEGROWTH = 1MB)
USE QLCuaHangTT

CREATE TABLE NhanVien(
MANV varchar(8) NOT NULL,
TENNV nvarchar(50) NOT NULL,
NGAYSINH date NOT NULL,
GIOITINH bit NOT NULL,
SDT nvarchar(10) NOT NULL,
DIACHI nvarchar(50),
EMAIL nvarchar(50), 
PRIMARY KEY (MANV)
)

CREATE TABLE NhaCungCap (
MANCC varchar(8) NOT NULL,
TENNCC nvarchar(50) NOT NULL,
TENSP nvarchar(50) NOT NULL,
DIACHI nvarchar(50) NOT NULL,
PRIMARY KEY (maNCC)
)
 
 CREATE TABLE KhachHang (
 MAKH varchar(8) NOT NULL,
 TENKH nvarchar(50) NOT NULL,
 SDT nvarchar(10) NOT NULL,
 GIOITINH bit NOT NULL,
 EMAIL nvarchar(50),
 PRIMARY KEY (MAKH)
 )

CREATE TABLE TaiKhoan (
MADANGNHAP varchar(8),
MATKHAU nvarchar(50),
PHANQUYEN nvarchar(50)
PRIMARY KEY (MADANGNHAP),
FOREIGN KEY (MADANGNHAP) REFERENCES NhanVien(MANV)
)

CREATE TABLE QuanAo (
MAQUANAO varchar(8)NOT NULL,
MANCC varchar(8) NOT NULL,
TENSP nvarchar(50) NOT NULL,
HINHANH nvarchar(100) NOT NULL,
LOAI nvarchar(20) NOT NULL,
SOLUONG int NOT NULL,
CHATLIEU nvarchar(20) NOT NULL, 
MAUSAC nvarchar(20) NOT NULL,
DONGIABAN Float NOT NULL, 
PRIMARY KEY (MAQUANAO),
FOREIGN KEY (MANCC) REFERENCES NhaCungCap(MANCC)
)


CREATE TABLE PhieuDatHang(
MAPHIEUDAT varchar(8) NOT NULL,
MAKH varchar(8) NOT NULL,
MANV varchar(8) NOT NULL,
NGAYDAT Date NOT NULL,
PRIMARY KEY (MAPHIEUDAT),
FOREIGN KEY (MANV) REFERENCES NhanVien(MANV),
FOREIGN KEY (MAKH) REFERENCES KhachHang(MAKH))


CREATE TABLE KhuyenMai (
MAKM varchar(8) NOT NULL,
NGAYBATDAU date NOT NULL,
NGAYKETTHUC date NOT NULL,
MUCGIAMGIA float NOT NULL,
PRIMARY KEY (MAKM)
)

 
 CREATE TABLE HoaDonNhapHang (
 MAHDNHAP varchar(8) NOT NULL,
 MANCC varchar(8) NOT NULL,
 MANV varchar(8) NOT NULL,
 NGAYNHAP date NOT NULL,
 PRIMARY KEY (MAHDNHAP),
 FOREIGN KEY (MANCC) REFERENCES NhaCungCap(MANCC),
 FOREIGN KEY (MANV) REFERENCES NhanVien(MANV),
 )
 
 CREATE TABLE HoaDon (
 MAHD varchar(8) NOT NULL,
 MAKH varchar(8) NOT NULL,
 MANV varchar(8) NOT NULL,
 NGAYLAPHD date NOT NULL,
 PRIMARY KEY (MAHD),
 FOREIGN KEY (MAKH) REFERENCES  KhachHang(MAKH),
 FOREIGN KEY (MANV) REFERENCES  NhanVien(MANV),
 )

 CREATE TABLE ChiTietPhieuDatHang (
 MAPHIEUDAT varchar(8) NOT NULL,
 MAQUANAO varchar(8) NOT NULL,
 SOLUONG int NOT NULL,
PRIMARY KEY (MAPHIEUDAT),
FOREIGN KEY (MAQUANAO) REFERENCES QuanAo(MAQUANAO),
FOREIGN KEY (MAPHIEUDAT) REFERENCES PhieuDatHang(MAPHIEUDAT)		
)

CREATE TABLE ChiTietHoaDonNhapHang (
MAHDNHAP varchar(8) NOT NULL,
MAQUANAO varchar(8) NOT NULL,
SOLUONG int NOT NULL,
DONGIANHAP float NOT NULL,
PRIMARY KEY (MAHDNHAP),
FOREIGN KEY (MAHDNHAP) REFERENCES HoaDonNhapHang (MAHDNHAP),
FOREIGN KEY (MAQUANAO) REFERENCES QuanAo(MAQUANAO)
)

CREATE TABLE ChiTietHoaDon (
MAHD varchar(8) NOT NULL,
MAKM varchar(8) NOT NULL,
MAQUANAO varchar(8) NOT NULL,
SOLUONG int NOT NULL,
DONGIA float NOT NULL,
PRIMARY KEY (MAHD),
FOREIGN KEY (MAHD) REFERENCES HoaDon (MAHD),
FOREIGN KEY (MAKM) REFERENCES KhuyenMai (MAKM),
FOREIGN KEY (MAQUANAO) REFERENCES QuanAo (MAQUANAO),
)