/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlthoitrang;

/**
 *
 * @author Acer
 */
public class ThongKe extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pn_left = new javax.swing.JPanel();
        scr_CTDT = new javax.swing.JScrollPane();
        tbl_chiTietDoanhThu = new javax.swing.JTable();
        lbl_chiTietDT = new javax.swing.JLabel();
        pn_right = new javax.swing.JPanel();
        lbl_thongKeDT = new javax.swing.JLabel();
        cmb_ngayThangNam = new javax.swing.JComboBox<>();
        lbl_luaChon = new javax.swing.JLabel();
        rad_bang = new javax.swing.JRadioButton();
        rad_cot = new javax.swing.JRadioButton();
        btn_thongKe = new javax.swing.JButton();
        pn_top = new javax.swing.JPanel();
        lbl_thongKe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_left.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_chiTietDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ngày/Tháng/Năm", "Sản Phẩm Bán", "Tổng Tiền Bán", "Tổng Giá Giảm", "Doanh Thu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scr_CTDT.setViewportView(tbl_chiTietDoanhThu);

        lbl_chiTietDT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_chiTietDT.setForeground(new java.awt.Color(0, 102, 255));
        lbl_chiTietDT.setText("Chi Tiết Doanh Thu");

        javax.swing.GroupLayout pn_leftLayout = new javax.swing.GroupLayout(pn_left);
        pn_left.setLayout(pn_leftLayout);
        pn_leftLayout.setHorizontalGroup(
            pn_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_chiTietDT, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(711, Short.MAX_VALUE))
            .addGroup(pn_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_leftLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scr_CTDT, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)))
        );
        pn_leftLayout.setVerticalGroup(
            pn_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_leftLayout.createSequentialGroup()
                .addComponent(lbl_chiTietDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_leftLayout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(scr_CTDT, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        pn_right.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_thongKeDT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_thongKeDT.setForeground(new java.awt.Color(255, 0, 51));
        lbl_thongKeDT.setText("Thống Kê Doanh Thu");

        cmb_ngayThangNam.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cmb_ngayThangNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày", "Tháng", "Năm" }));
        cmb_ngayThangNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ngayThangNamActionPerformed(evt);
            }
        });

        lbl_luaChon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_luaChon.setForeground(new java.awt.Color(255, 0, 51));
        lbl_luaChon.setText("Lựa Chọn Hiển Thị");

        rad_bang.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rad_bang.setText("Dạng Bảng");
        rad_bang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_bangActionPerformed(evt);
            }
        });

        rad_cot.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rad_cot.setText("Dạng Cột");

        btn_thongKe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_thongKe.setIcon(new javax.swing.ImageIcon("D:\\DOANPTUD\\QLThoiTrang\\icon\\analytics.png")); // NOI18N
        btn_thongKe.setText("Thống Kê Doanh Thu");
        btn_thongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_rightLayout = new javax.swing.GroupLayout(pn_right);
        pn_right.setLayout(pn_rightLayout);
        pn_rightLayout.setHorizontalGroup(
            pn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_rightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_thongKeDT, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_rightLayout.createSequentialGroup()
                        .addComponent(cmb_ngayThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_luaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_rightLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_rightLayout.createSequentialGroup()
                        .addComponent(btn_thongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_rightLayout.createSequentialGroup()
                        .addGroup(pn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rad_cot)
                            .addComponent(rad_bang))
                        .addGap(91, 91, 91))))
        );
        pn_rightLayout.setVerticalGroup(
            pn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_rightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_thongKeDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(pn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_ngayThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_luaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_bang)
                .addGap(27, 27, 27)
                .addComponent(rad_cot)
                .addGap(209, 209, 209)
                .addComponent(btn_thongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pn_top.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_thongKe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_thongKe.setText("THỐNG KÊ");

        javax.swing.GroupLayout pn_topLayout = new javax.swing.GroupLayout(pn_top);
        pn_top.setLayout(pn_topLayout);
        pn_topLayout.setHorizontalGroup(
            pn_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_topLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_thongKe)
                .addGap(595, 595, 595))
        );
        pn_topLayout.setVerticalGroup(
            pn_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_topLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_thongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pn_left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_thongKeActionPerformed

    private void cmb_ngayThangNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ngayThangNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_ngayThangNamActionPerformed

    private void rad_bangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_bangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_bangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thongKe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_ngayThangNam;
    private javax.swing.JLabel lbl_chiTietDT;
    private javax.swing.JLabel lbl_luaChon;
    private javax.swing.JLabel lbl_thongKe;
    private javax.swing.JLabel lbl_thongKeDT;
    private javax.swing.JPanel pn_left;
    private javax.swing.JPanel pn_right;
    private javax.swing.JPanel pn_top;
    private javax.swing.JRadioButton rad_bang;
    private javax.swing.JRadioButton rad_cot;
    private javax.swing.JScrollPane scr_CTDT;
    private javax.swing.JTable tbl_chiTietDoanhThu;
    // End of variables declaration//GEN-END:variables
}
