///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package gui;
//
//import java.awt.Color;
//
//import javax.swing.JFrame;
//import javax.swing.JPanel;
//
//import entity.TaiKhoan;
//
///**
// *
// * @author ThanhDinh
// */
//public class TrangChu1 extends JFrame {
//
//    /**
//     * Creates new form Home
//     */
//    public TrangChu1(TaiKhoan tk) {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        jPanel3 = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        jPanel2 = new javax.swing.JPanel();
//        lb_nhanVien = new javax.swing.JLabel();
//        lb_maNhanVien = new javax.swing.JLabel();
//        txt_maNhanVien = new javax.swing.JTextField();
//        lb_hoTenNhanVien = new javax.swing.JLabel();
//        txt_hoTenNhanVien = new javax.swing.JTextField();
//        SideBar = new javax.swing.JPanel();
//        itemNhanVien = new javax.swing.JPanel();
//        lblNhanVien = new javax.swing.JLabel();
//        lblQuanLyNhanVien = new javax.swing.JLabel();
//        lblTimKiemNhanVien = new javax.swing.JLabel();
//        lblDatHang = new javax.swing.JLabel();
//        lblThongKe = new javax.swing.JLabel();
//        lblLapHoaDon = new javax.swing.JLabel();
//        lblXuatHoaDon = new javax.swing.JLabel();
//        itemKhachHang = new javax.swing.JPanel();
//        lblKhachHang = new javax.swing.JLabel();
//        lblQuanLyKhachHang = new javax.swing.JLabel();
//        lblTimKiemKhachHang = new javax.swing.JLabel();
//        itemSanPham = new javax.swing.JPanel();
//        pnlSanPham = new javax.swing.JPanel();
//        lblSanPham = new javax.swing.JLabel();
//        pnlQuanLySanPham = new javax.swing.JPanel();
//        lblQuanLySanPham = new javax.swing.JLabel();
//        pnlTimKiemSanPham = new javax.swing.JPanel();
//        lblTimKiemSanPham = new javax.swing.JLabel();
//        pnlQuanLyKho = new javax.swing.JPanel();
//        lblQuanLyKho = new javax.swing.JLabel();
//        pnlQuanLyKhuyenMai = new javax.swing.JPanel();
//        lblQuanLyKhuyenMai = new javax.swing.JLabel();
//        jMenuBar1 = new javax.swing.JMenuBar();
//        jMenu1 = new javax.swing.JMenu();
//        jMenu2 = new javax.swing.JMenu();
//        menu_quanLyNhanVien = new javax.swing.JMenuItem();
//        menu_timKiemNhanVien = new javax.swing.JMenuItem();
//        menu_datHang = new javax.swing.JMenuItem();
//        menu_thongKe = new javax.swing.JMenuItem();
//        menu_lapHoaDon = new javax.swing.JMenuItem();
//        menu_xuatHoaDon = new javax.swing.JMenuItem();
//        jMenu3 = new javax.swing.JMenu();
//        menu_quanLyKhachHang = new javax.swing.JMenuItem();
//        menu_timKiemKhachHang = new javax.swing.JMenuItem();
//        jMenu4 = new javax.swing.JMenu();
//        menu_quanLySanPham = new javax.swing.JMenuItem();
//        menu_timKiemSanPham = new javax.swing.JMenuItem();
//        menu_quanLyKho = new javax.swing.JMenuItem();
//        menu_quanLyKhuyenMai = new javax.swing.JMenuItem();
//        jMenu5 = new javax.swing.JMenu();
//        menu_quanLyNhaCungCap = new javax.swing.JMenuItem();
//        menu_timKiemNhaCungCap = new javax.swing.JMenuItem();
//        jMenu6 = new javax.swing.JMenu();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setTitle(".");
//
//        jPanel1.setToolTipText("");
//
//        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//
//        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Nhom18_PTUD_DoAn\\QLThoiTrang\\icon\\Shop.jpg")); // NOI18N
//
//        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//        jPanel3.setLayout(jPanel3Layout);
//        jPanel3Layout.setHorizontalGroup(
//            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel3Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jLabel1)
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        jPanel3Layout.setVerticalGroup(
//            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel3Layout.createSequentialGroup()
//                .addGap(23, 23, 23)
//                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addContainerGap())
//        );
//
//        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//
//        lb_nhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        lb_nhanVien.setText("Nhân Viên");
//
//        lb_maNhanVien.setText("Mã Nhân Viên ");
//
//        txt_maNhanVien.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txt_maNhanVienActionPerformed(evt);
//            }
//        });
//
//        lb_hoTenNhanVien.setText("Họ Tên Nhân Viên");
//
//        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//        jPanel2.setLayout(jPanel2Layout);
//        jPanel2Layout.setHorizontalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel2Layout.createSequentialGroup()
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(txt_maNhanVien, javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addComponent(txt_hoTenNhanVien)
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addComponent(lb_maNhanVien))
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addGap(26, 26, 26)
//                                .addComponent(lb_nhanVien))
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addComponent(lb_hoTenNhanVien)))
//                        .addGap(0, 53, Short.MAX_VALUE)))
//                .addContainerGap())
//        );
//        jPanel2Layout.setVerticalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel2Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(lb_nhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addComponent(lb_maNhanVien)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(txt_maNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(lb_hoTenNhanVien)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(txt_hoTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//
//        SideBar.setToolTipText("");
//        SideBar.setMaximumSize(new java.awt.Dimension(129, 442));
//        SideBar.setMinimumSize(new java.awt.Dimension(129, 442));
//        SideBar.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                SideBarMouseClicked(evt);
//            }
//        });
//
//        itemNhanVien.setBackground(new java.awt.Color(204, 255, 204));
//        itemNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                ClickedNhanVien(evt);
//            }
//        });
//        itemNhanVien.setLayout(new javax.swing.BoxLayout(itemNhanVien, javax.swing.BoxLayout.Y_AXIS));
//
//        lblNhanVien.setBackground(new java.awt.Color(204, 255, 204));
//        lblNhanVien.setText("Nhân Viên");
//        lblNhanVien.setMaximumSize(new java.awt.Dimension(117, 40));
//        lblNhanVien.setMinimumSize(new java.awt.Dimension(117, 40));
//        lblNhanVien.setPreferredSize(new java.awt.Dimension(117, 40));
//        itemNhanVien.add(lblNhanVien);
//
//        lblQuanLyNhanVien.setText("Quản Lý Nhân Viên");
//        lblQuanLyNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        lblQuanLyNhanVien.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblQuanLyNhanVien.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblQuanLyNhanVien.setPreferredSize(new java.awt.Dimension(120, 22));
//        itemNhanVien.add(lblQuanLyNhanVien);
//
//        lblTimKiemNhanVien.setText("Tìm Kiếm Nhân Viên");
//        lblTimKiemNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        lblTimKiemNhanVien.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblTimKiemNhanVien.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblTimKiemNhanVien.setPreferredSize(new java.awt.Dimension(120, 22));
//        itemNhanVien.add(lblTimKiemNhanVien);
//
//        lblDatHang.setText("Đặt Hàng");
//        lblDatHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        lblDatHang.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblDatHang.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblDatHang.setPreferredSize(new java.awt.Dimension(120, 22));
//        itemNhanVien.add(lblDatHang);
//
//        lblThongKe.setText("Thống Kê");
//        lblThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        lblThongKe.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblThongKe.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblThongKe.setPreferredSize(new java.awt.Dimension(120, 22));
//        itemNhanVien.add(lblThongKe);
//
//        lblLapHoaDon.setText("Lập Hóa Đơn");
//        lblLapHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        lblLapHoaDon.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblLapHoaDon.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblLapHoaDon.setPreferredSize(new java.awt.Dimension(120, 22));
//        itemNhanVien.add(lblLapHoaDon);
//
//        lblXuatHoaDon.setText("Xuất Hóa Đơn");
//        lblXuatHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        lblXuatHoaDon.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblXuatHoaDon.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblXuatHoaDon.setPreferredSize(new java.awt.Dimension(120, 22));
//        itemNhanVien.add(lblXuatHoaDon);
//
//        SideBar.add(itemNhanVien);
//
//        itemKhachHang.setBackground(new java.awt.Color(204, 255, 204));
//        itemKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                ClickedKhachHang(evt);
//            }
//        });
//        itemKhachHang.setLayout(new javax.swing.BoxLayout(itemKhachHang, javax.swing.BoxLayout.Y_AXIS));
//
//        lblKhachHang.setText("Khách Hàng");
//        lblKhachHang.setMaximumSize(new java.awt.Dimension(117, 40));
//        lblKhachHang.setMinimumSize(new java.awt.Dimension(117, 40));
//        lblKhachHang.setPreferredSize(new java.awt.Dimension(117, 40));
//        itemKhachHang.add(lblKhachHang);
//
//        lblQuanLyKhachHang.setText("Quản Lý Khách Hàng");
//        lblQuanLyKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        lblQuanLyKhachHang.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblQuanLyKhachHang.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblQuanLyKhachHang.setPreferredSize(new java.awt.Dimension(120, 22));
//        itemKhachHang.add(lblQuanLyKhachHang);
//
//        lblTimKiemKhachHang.setText("Tìm Kiếm Khách Hàng");
//        lblTimKiemKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        lblTimKiemKhachHang.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblTimKiemKhachHang.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblTimKiemKhachHang.setPreferredSize(new java.awt.Dimension(120, 22));
//        itemKhachHang.add(lblTimKiemKhachHang);
//
//        SideBar.add(itemKhachHang);
//
//        itemSanPham.setBackground(new java.awt.Color(255, 255, 255));
//        itemSanPham.setMaximumSize(new java.awt.Dimension(117, 130));
//        itemSanPham.setMinimumSize(new java.awt.Dimension(117, 130));
//        itemSanPham.setPreferredSize(new java.awt.Dimension(117, 130));
//        itemSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                itemSanPhamMouseClicked(evt);
//            }
//        });
//        itemSanPham.setLayout(new javax.swing.BoxLayout(itemSanPham, javax.swing.BoxLayout.Y_AXIS));
//
//        pnlSanPham.setBackground(new java.awt.Color(204, 255, 204));
//        pnlSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        pnlSanPham.setMaximumSize(new java.awt.Dimension(117, 40));
//        pnlSanPham.setMinimumSize(new java.awt.Dimension(117, 40));
//        pnlSanPham.setPreferredSize(new java.awt.Dimension(117, 40));
//        pnlSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                ClickedSanPham(evt);
//            }
//        });
//
//        lblSanPham.setForeground(new java.awt.Color(255, 0, 51));
//        lblSanPham.setText("Sản Phẩm");
//        lblSanPham.setMaximumSize(new java.awt.Dimension(117, 40));
//        lblSanPham.setMinimumSize(new java.awt.Dimension(117, 40));
//        lblSanPham.setPreferredSize(new java.awt.Dimension(117, 40));
//        lblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                lblSanPhamMouseClicked(evt);
//            }
//        });
//
//        javax.swing.GroupLayout pnlSanPhamLayout = new javax.swing.GroupLayout(pnlSanPham);
//        pnlSanPham.setLayout(pnlSanPhamLayout);
//        pnlSanPhamLayout.setHorizontalGroup(
//            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(lblSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 115, Short.MAX_VALUE)
//        );
//        pnlSanPhamLayout.setVerticalGroup(
//            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(pnlSanPhamLayout.createSequentialGroup()
//                .addComponent(lblSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//
//        itemSanPham.add(pnlSanPham);
//
//        pnlQuanLySanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        pnlQuanLySanPham.setMaximumSize(new java.awt.Dimension(120, 22));
//        pnlQuanLySanPham.setMinimumSize(new java.awt.Dimension(120, 22));
//        pnlQuanLySanPham.setPreferredSize(new java.awt.Dimension(120, 22));
//
//        lblQuanLySanPham.setText("Quản Lý Sản Phẩm");
//        lblQuanLySanPham.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblQuanLySanPham.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblQuanLySanPham.setPreferredSize(new java.awt.Dimension(120, 22));
//
//        javax.swing.GroupLayout pnlQuanLySanPhamLayout = new javax.swing.GroupLayout(pnlQuanLySanPham);
//        pnlQuanLySanPham.setLayout(pnlQuanLySanPhamLayout);
//        pnlQuanLySanPhamLayout.setHorizontalGroup(
//            pnlQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(lblQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 115, Short.MAX_VALUE)
//        );
//        pnlQuanLySanPhamLayout.setVerticalGroup(
//            pnlQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(pnlQuanLySanPhamLayout.createSequentialGroup()
//                .addComponent(lblQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//
//        itemSanPham.add(pnlQuanLySanPham);
//
//        pnlTimKiemSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        pnlTimKiemSanPham.setMaximumSize(new java.awt.Dimension(120, 22));
//        pnlTimKiemSanPham.setMinimumSize(new java.awt.Dimension(120, 22));
//        pnlTimKiemSanPham.setPreferredSize(new java.awt.Dimension(120, 22));
//
//        lblTimKiemSanPham.setText("Tìm Kiếm Sản Phẩm");
//        lblTimKiemSanPham.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblTimKiemSanPham.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblTimKiemSanPham.setPreferredSize(new java.awt.Dimension(120, 22));
//
//        javax.swing.GroupLayout pnlTimKiemSanPhamLayout = new javax.swing.GroupLayout(pnlTimKiemSanPham);
//        pnlTimKiemSanPham.setLayout(pnlTimKiemSanPhamLayout);
//        pnlTimKiemSanPhamLayout.setHorizontalGroup(
//            pnlTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(lblTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 115, Short.MAX_VALUE)
//        );
//        pnlTimKiemSanPhamLayout.setVerticalGroup(
//            pnlTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(pnlTimKiemSanPhamLayout.createSequentialGroup()
//                .addComponent(lblTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//
//        itemSanPham.add(pnlTimKiemSanPham);
//
//        pnlQuanLyKho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        pnlQuanLyKho.setMaximumSize(new java.awt.Dimension(120, 22));
//        pnlQuanLyKho.setMinimumSize(new java.awt.Dimension(120, 22));
//
//        lblQuanLyKho.setText("Quản Lý Kho");
//        lblQuanLyKho.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblQuanLyKho.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblQuanLyKho.setPreferredSize(new java.awt.Dimension(120, 22));
//
//        javax.swing.GroupLayout pnlQuanLyKhoLayout = new javax.swing.GroupLayout(pnlQuanLyKho);
//        pnlQuanLyKho.setLayout(pnlQuanLyKhoLayout);
//        pnlQuanLyKhoLayout.setHorizontalGroup(
//            pnlQuanLyKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(lblQuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 115, Short.MAX_VALUE)
//        );
//        pnlQuanLyKhoLayout.setVerticalGroup(
//            pnlQuanLyKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(pnlQuanLyKhoLayout.createSequentialGroup()
//                .addComponent(lblQuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//
//        itemSanPham.add(pnlQuanLyKho);
//
//        pnlQuanLyKhuyenMai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        pnlQuanLyKhuyenMai.setMaximumSize(new java.awt.Dimension(120, 22));
//        pnlQuanLyKhuyenMai.setMinimumSize(new java.awt.Dimension(120, 22));
//
//        lblQuanLyKhuyenMai.setText("Quản Lý Khuyến Mãi");
//        lblQuanLyKhuyenMai.setMaximumSize(new java.awt.Dimension(120, 22));
//        lblQuanLyKhuyenMai.setMinimumSize(new java.awt.Dimension(120, 22));
//        lblQuanLyKhuyenMai.setPreferredSize(new java.awt.Dimension(120, 22));
//
//        javax.swing.GroupLayout pnlQuanLyKhuyenMaiLayout = new javax.swing.GroupLayout(pnlQuanLyKhuyenMai);
//        pnlQuanLyKhuyenMai.setLayout(pnlQuanLyKhuyenMaiLayout);
//        pnlQuanLyKhuyenMaiLayout.setHorizontalGroup(
//            pnlQuanLyKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(lblQuanLyKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 115, Short.MAX_VALUE)
//        );
//        pnlQuanLyKhuyenMaiLayout.setVerticalGroup(
//            pnlQuanLyKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(pnlQuanLyKhuyenMaiLayout.createSequentialGroup()
//                .addComponent(lblQuanLyKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//
//        itemSanPham.add(pnlQuanLyKhuyenMai);
//
//        SideBar.add(itemSanPham);
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(SideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())
//        );
//
//        jMenu1.setText("Trang Chủ");
//        jMenuBar1.add(jMenu1);
//
//        jMenu2.setText("Nhân Viên");
//
//        menu_quanLyNhanVien.setText("Quản Lý Nhân Viên");
//        menu_quanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                menu_quanLyNhanVienActionPerformed(evt);
//            }
//        });
//        jMenu2.add(menu_quanLyNhanVien);
//
//        menu_timKiemNhanVien.setText("Tìm Kiếm Nhân Viên");
//        jMenu2.add(menu_timKiemNhanVien);
//
//        menu_datHang.setText("Đặt Hàng");
//        jMenu2.add(menu_datHang);
//
//        menu_thongKe.setText("Thống Kê");
//        jMenu2.add(menu_thongKe);
//
//        menu_lapHoaDon.setText("Lập Hóa Đơn");
//        jMenu2.add(menu_lapHoaDon);
//
//        menu_xuatHoaDon.setText("Xuất Hóa Đơn");
//        jMenu2.add(menu_xuatHoaDon);
//
//        jMenuBar1.add(jMenu2);
//
//        jMenu3.setText("Khách Hàng");
//
//        menu_quanLyKhachHang.setText("Quản Lý Khách Hàng");
//        jMenu3.add(menu_quanLyKhachHang);
//
//        menu_timKiemKhachHang.setText("Tìm Kiếm Khách Hàng");
//        jMenu3.add(menu_timKiemKhachHang);
//
//        jMenuBar1.add(jMenu3);
//
//        jMenu4.setText("Sản Phẩm");
//
//        menu_quanLySanPham.setText("Quản Lý Sản Phẩm");
//        jMenu4.add(menu_quanLySanPham);
//
//        menu_timKiemSanPham.setText("Tìm Kiếm Sản Phẩm");
//        jMenu4.add(menu_timKiemSanPham);
//
//        menu_quanLyKho.setText("Quản Lý Kho");
//        jMenu4.add(menu_quanLyKho);
//
//        menu_quanLyKhuyenMai.setText("Quản Lý Khuyến Mãi");
//        jMenu4.add(menu_quanLyKhuyenMai);
//
//        jMenuBar1.add(jMenu4);
//
//        jMenu5.setText("Nhà Cung Cấp");
//
//        menu_quanLyNhaCungCap.setText("Quản Lý Nhà Cung Cấp");
//        jMenu5.add(menu_quanLyNhaCungCap);
//
//        menu_timKiemNhaCungCap.setText("Tìm Kiếm Nhà Cung Cấp");
//        jMenu5.add(menu_timKiemNhaCungCap);
//
//        jMenuBar1.add(jMenu5);
//
//        jMenu6.setText("Đăng Xuất");
//        jMenuBar1.add(jMenu6);
//
//        setJMenuBar(jMenuBar1);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void txt_maNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNhanVienActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txt_maNhanVienActionPerformed
//
//    private void menu_quanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_quanLyNhanVienActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_menu_quanLyNhanVienActionPerformed
//
//    private void SideBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SideBarMouseClicked
//
//    }//GEN-LAST:event_SideBarMouseClicked
//
//    private void ClickedKhachHang(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickedKhachHang
//        if (evt.getSource().equals(itemKhachHang)) {
//            ThuLaiNhanVien(itemNhanVien);
//            ThuLaiSanPham(itemSanPham);
//            SideBarMouseClickedItem(itemKhachHang);
//        }
//    }//GEN-LAST:event_ClickedKhachHang
//
//    private void ThuLaiKhachHang(JPanel panel) {
//        for (int i = 1; i < panel.getComponentCount(); i++) {
//            panel.getComponent(i).setVisible(false);
//        }
//        panel.setBackground(new Color(204, 255, 204));
//    }
//
//    private void ClickedNhanVien(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickedNhanVien
//        if (evt.getSource().equals(itemNhanVien)) {
//            ThuLaiKhachHang(itemKhachHang);
//            ThuLaiSanPham(itemSanPham);
//            SideBarMouseClickedItem(itemNhanVien);
//        }
//    }//GEN-LAST:event_ClickedNhanVien
//
//    private void ThuLaiNhanVien(JPanel panel) {
//        for (int i = 1; i < panel.getComponentCount(); i++) {
//            panel.getComponent(i).setVisible(false);
//        }
//        panel.setBackground(new Color(204, 255, 204));
//    }
//
//    private void ClickedSanPham(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickedSanPham
//        if (evt.getSource().equals(pnlSanPham)) {
//            ThuLaiKhachHang(itemKhachHang);
//            ThuLaiNhanVien(itemNhanVien);
//            if (pnlSanPham.getForeground().equals(new Color(255, 0, 51))) {
//                for (int i = 1; i < itemSanPham.getComponentCount(); ++i) {
//                    itemSanPham.getComponent(i).setVisible(true);
//                }
//                pnlSanPham.setBackground(Color.red);
//            } else {
//                for (int i = 1; i < itemSanPham.getComponentCount(); i++) {
//                    itemSanPham.getComponent(i).setVisible(false);
//                }
//                pnlSanPham.setBackground(new Color(204, 255, 204));
//            }
//            repaint();  // node lai man hinh 
//        }
//    }//GEN-LAST:event_ClickedSanPham
//
//    private void itemSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSanPhamMouseClicked
//
//    }//GEN-LAST:event_itemSanPhamMouseClicked
//
//    private void lblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSanPhamMouseClicked
//        // TODO add your handling code here:
//    }//GEN-LAST:event_lblSanPhamMouseClicked
//
//    private void ThuLaiSanPham(JPanel panel) {
//        for (int i = 1; i < panel.getComponentCount(); i++) {
//            panel.getComponent(i).setVisible(false);
//        }
//        panel.setBackground(new Color(204, 255, 204));
//    }
//
//    public void SideBarMouseClickedItem(JPanel panel) {
//        if (panel.getBackground().equals(new Color(204, 255, 204))) {
//            for (int i = 1; i < panel.getComponentCount(); i++) {
//                panel.getComponent(i).setVisible(true);
//            }
//            panel.setBackground(Color.red);
//        } else {
//            for (int i = 1; i < panel.getComponentCount(); i++) {
//                panel.getComponent(i).setVisible(false);
//            }
//            panel.setBackground(new Color(204, 255, 204));
//        }
//        repaint();  // node lai man hinh 
//    }
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TrangChu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TrangChu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TrangChu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TrangChu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JPanel SideBar;
//    private javax.swing.JPanel itemKhachHang;
//    private javax.swing.JPanel itemNhanVien;
//    private javax.swing.JPanel itemSanPham;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JMenu jMenu1;
//    private javax.swing.JMenu jMenu2;
//    private javax.swing.JMenu jMenu3;
//    private javax.swing.JMenu jMenu4;
//    private javax.swing.JMenu jMenu5;
//    private javax.swing.JMenu jMenu6;
//    private javax.swing.JMenuBar jMenuBar1;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPanel jPanel2;
//    private javax.swing.JPanel jPanel3;
//    private javax.swing.JLabel lb_hoTenNhanVien;
//    private javax.swing.JLabel lb_maNhanVien;
//    private javax.swing.JLabel lb_nhanVien;
//    private javax.swing.JLabel lblDatHang;
//    private javax.swing.JLabel lblKhachHang;
//    private javax.swing.JLabel lblLapHoaDon;
//    private javax.swing.JLabel lblNhanVien;
//    private javax.swing.JLabel lblQuanLyKhachHang;
//    private javax.swing.JLabel lblQuanLyKho;
//    private javax.swing.JLabel lblQuanLyKhuyenMai;
//    private javax.swing.JLabel lblQuanLyNhanVien;
//    private javax.swing.JLabel lblQuanLySanPham;
//    private javax.swing.JLabel lblSanPham;
//    private javax.swing.JLabel lblThongKe;
//    private javax.swing.JLabel lblTimKiemKhachHang;
//    private javax.swing.JLabel lblTimKiemNhanVien;
//    private javax.swing.JLabel lblTimKiemSanPham;
//    private javax.swing.JLabel lblXuatHoaDon;
//    private javax.swing.JMenuItem menu_datHang;
//    private javax.swing.JMenuItem menu_lapHoaDon;
//    private javax.swing.JMenuItem menu_quanLyKhachHang;
//    private javax.swing.JMenuItem menu_quanLyKho;
//    public javax.swing.JMenuItem menu_quanLyKhuyenMai;
//    private javax.swing.JMenuItem menu_quanLyNhaCungCap;
//    private javax.swing.JMenuItem menu_quanLyNhanVien;
//    private javax.swing.JMenuItem menu_quanLySanPham;
//    private javax.swing.JMenuItem menu_thongKe;
//    private javax.swing.JMenuItem menu_timKiemKhachHang;
//    private javax.swing.JMenuItem menu_timKiemNhaCungCap;
//    private javax.swing.JMenuItem menu_timKiemNhanVien;
//    private javax.swing.JMenuItem menu_timKiemSanPham;
//    private javax.swing.JMenuItem menu_xuatHoaDon;
//    private javax.swing.JPanel pnlQuanLyKho;
//    private javax.swing.JPanel pnlQuanLyKhuyenMai;
//    private javax.swing.JPanel pnlQuanLySanPham;
//    private javax.swing.JPanel pnlSanPham;
//    private javax.swing.JPanel pnlTimKiemSanPham;
//    private javax.swing.JTextField txt_hoTenNhanVien;
//    private javax.swing.JTextField txt_maNhanVien;
//    // End of variables declaration//GEN-END:variables
//}
